print("RUNNING report_html.py")
from summary import generate_summary

def generate_html_report(csv_path, output_file="report.html"):
    s = generate_summary(csv_path)

    rows = ""
    for k, v in s["by_category"].items():
        rows += f"<tr><td>{k.capitalize()}</td><td>{v}</td></tr>"

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>TaxLabs – Crypto Tax Summary</title>
<style>
    body {{
        font-family: Arial, sans-serif;
        background: #0b0f1a;
        color: #eaeaf0;
        padding: 40px;
    }}
    .card {{
        max-width: 800px;
        margin: auto;
        background: #131a2a;
        border-radius: 12px;
        padding: 30px;
        box-shadow: 0 10px 40px rgba(0,0,0,0.4);
    }}
    h1 {{
        margin-top: 0;
        color: #6ddcff;
    }}
    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }}
    th, td {{
        padding: 10px;
        border-bottom: 1px solid #222a44;
        text-align: left;
    }}
    .highlight {{
        background: #1c2440;
        padding: 15px;
        border-radius: 8px;
        margin: 20px 0;
    }}
    .footer {{
        font-size: 12px;
        opacity: 0.7;
        margin-top: 30px;
    }}
</style>
</head>

<body>
<div class="card">
    <h1>TaxLabs – Crypto Tax Checkup</h1>

    <p><strong>Total transactions reviewed:</strong> {s['total_transactions']}</p>

    <h3>Transaction breakdown</h3>
    <table>
        <tr><th>Type</th><th>Count</th></tr>
        {rows}
    </table>

    <div class="highlight">
        <p><strong>⚠️ Likely taxable events:</strong> {s['likely_taxable_events']}</p>
        <p><strong>Non-taxable events:</strong> {s['non_taxable_events']}</p>
    </div>

    <div class="highlight">
        <p><strong>💰 Estimated net USD flow:</strong> ${s['net_usd_flow']}</p>
    </div>

    <h3>What to do next</h3>
    <ul>
        <li>Review sells, swaps, and income events carefully</li>
        <li>Share this summary with your accountant if filing soon</li>
        <li>Use this as a checklist before tax software or professional review</li>
    </ul>

    <div class="footer">
        This report is informational only and not tax advice.<br>
        Generated by TaxLabs.
    </div>
</div>
</body>
</html>
"""

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"HTML report generated: {output_file}")

if __name__ == "__main__":
    generate_html_report("sample.csv")
