from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch


def generate_pdf(df, buffer):
    """
    Generate a simple PDF tax report from a pandas DataFrame.
    Writes directly into the provided buffer (BytesIO).
    """

    c = canvas.Canvas(buffer, pagesize=LETTER)
    width, height = LETTER

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, "TaxLabs Report")

    # Subtitle
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.4 * inch, "Generated by TaxLabs")

    # Start table position
    y = height - 2 * inch
    c.setFont("Helvetica", 9)

    if df is None or df.empty:
        c.drawString(1 * inch, y, "No data available.")
    else:
        # Header
        headers = list(df.columns)
        x_positions = [1 * inch + i * 1.5 * inch for i in range(len(headers))]

        c.setFont("Helvetica-Bold", 9)
        for x, header in zip(x_positions, headers):
            c.drawString(x, y, str(header))

        y -= 0.25 * inch
        c.setFont("Helvetica", 9)

        # Rows
        for _, row in df.iterrows():
            if y < 1 * inch:
                c.showPage()
                c.setFont("Helvetica", 9)
                y = height - 1 * inch

            for x, value in zip(x_positions, row):
                c.drawString(x, y, str(value))

            y -= 0.2 * inch

    c.save()
