import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
from datetime import datetime
import os

def generate_pdf(csv_path, output_path="report.pdf"):
    df = pd.read_csv(csv_path)
    df.columns = [c.lower() for c in df.columns]

    total_transactions = len(df)
    breakdown = df["type"].value_counts().to_dict()
    taxable_types = {"sell", "swap", "income"}
    taxable_count = len(df[df["type"].isin(taxable_types)])
    net_usd_flow = int(df["usd_value"].sum())

    wallet_label = os.path.basename(csv_path)
    today = datetime.now().strftime("%Y-%m-%d")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    content = []

    # Title
    content.append(Paragraph(
        "<b>TaxLabs — Crypto Tax Checkup</b>", styles["Title"]
    ))
    content.append(Spacer(1, 12))

    content.append(Paragraph(
        "A clear, human-readable summary of your crypto activity — before tax season decides for you.",
        styles["Normal"]
    ))
    content.append(Spacer(1, 8))

    content.append(Paragraph(
        f"<font size=9 color=grey>Generated on: {today} &nbsp;&nbsp;|&nbsp;&nbsp; Source: {wallet_label}</font>",
        styles["Normal"]
    ))
    content.append(Spacer(1, 20))

    # Overview
    content.append(Paragraph("<b>Activity overview</b>", styles["Heading2"]))
    content.append(Spacer(1, 6))
    content.append(Paragraph(f"Total transactions reviewed: <b>{total_transactions}</b>", styles["Normal"]))
    content.append(Spacer(1, 12))

    table_data = [["Type", "Count"]]
    for k, v in breakdown.items():
        table_data.append([k.capitalize(), v])

    table = Table(table_data, colWidths=[200, 100])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("ALIGN", (1,1), (-1,-1), "RIGHT"),
        ("FONT", (0,0), (-1,0), "Helvetica-Bold"),
    ]))
    content.append(table)
    content.append(Spacer(1, 16))

    # Tax notice
    content.append(Paragraph(
        f"<b>⚠ {taxable_count} events are likely taxable.</b><br/>"
        "These typically come from sells, swaps, or crypto income.",
        styles["Normal"]
    ))
    content.append(Spacer(1, 12))

    content.append(Paragraph(
        f"<b>Estimated net USD activity:</b> ${net_usd_flow}",
        styles["Normal"]
    ))
    content.append(Spacer(1, 16))

    # Next steps
    content.append(Paragraph("<b>What to do next</b>", styles["Heading3"]))
    content.append(Spacer(1, 6))
    content.append(Paragraph("• Review sells, swaps, and income events", styles["Normal"]))
    content.append(Paragraph("• Share this report with your accountant if filing soon", styles["Normal"]))
    content.append(Paragraph("• Use this as a clarity check before tax software or professional review", styles["Normal"]))
    content.append(Spacer(1, 20))

    content.append(Paragraph(
        "<font size=8 color=grey>"
        "This report is for informational clarity only and not tax advice.<br/>"
        "Generated by TaxLabs — clarity before compliance."
        "</font>",
        styles["Normal"]
    ))

    doc.build(content)
    print("PDF report generated: report.pdf")

if __name__ == "__main__":
    generate_pdf("sample.csv")
