import pandas as pd
from datetime import datetime


def generate_report(csv_path, output_html_path):
    df = pd.read_csv(csv_path)
    df.columns = [c.lower() for c in df.columns]

    total_transactions = len(df)
    counts = df["type"].value_counts().to_dict()

    taxable_types = {"sell", "swap", "income"}
    taxable_events = sum(counts.get(t, 0) for t in taxable_types)

    net_usd = int(df["usd_value"].sum())
    today = datetime.today().strftime("%Y-%m-%d")

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>TaxLabs — Crypto Tax Checkup</title>

<style>
body {{
  background: radial-gradient(circle at top, #0f172a, #020617);
  color: #e5e7eb;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  margin: 0;
  padding: 56px 0;
}}

.container {{
  max-width: 720px;
  margin: auto;
  background: linear-gradient(180deg, #0b1220, #020617);
  border-radius: 18px;
  padding: 44px;
  box-shadow: 0 25px 80px rgba(0,0,0,0.6);
}}

h1 {{
  color: #38bdf8;
  font-size: 1.9rem;
  margin-bottom: 8px;
}}

.subtitle {{
  color: #cbd5f5;
  font-size: 0.95rem;
  line-height: 1.5;
  margin-bottom: 22px;
}}

.meta {{
  display: flex;
  justify-content: space-between;
  font-size: 0.75rem;
  color: #94a3b8;
  margin-bottom: 36px;
}}

.section-title {{
  font-size: 1.15rem;
  margin: 36px 0 16px;
  color: #f8fafc;
  border-bottom: 1px solid #1e293b;
  padding-bottom: 8px;
}}

table {{
  width: 100%;
  border-collapse: collapse;
  margin-top: 16px;
}}

th, td {{
  padding: 12px 10px;
  text-align: left;
}}

th {{
  font-size: 0.7rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: #94a3b8;
}}

tr {{
  border-bottom: 1px solid #1e293b;
}}

.alert {{
  margin-top: 26px;
  padding: 18px 20px;
  border-radius: 14px;
  font-weight: 600;
  font-size: 0.95rem;
}}

.alert.warning {{
  background: linear-gradient(90deg, #3f2d0c, #2a1c06);
  color: #fde68a;
  border-left: 5px solid #f59e0b;
}}

.alert.success {{
  background: linear-gradient(90deg, #052e1a, #022015);
  color: #86efac;
  border-left: 5px solid #22c55e;
  font-size: 1.1rem;
}}

.footer {{
  margin-top: 40px;
  font-size: 0.7rem;
  color: #64748b;
  text-align: center;
}}
</style>
</head>

<body>
<div class="container">

<h1>TaxLabs — Crypto Tax Checkup</h1>

<p class="subtitle">
A clear, human-readable summary of your crypto activity — before tax season decides for you.
</p>

<div class="meta">
  <span>Generated on: {today}</span>
  <span>Source: {csv_path}</span>
</div>

<div class="section-title">Activity overview</div>

<p><strong>Total transactions reviewed:</strong> {total_transactions}</p>

<table>
<tr><th>Type</th><th>Count</th></tr>
<tr><td>Buy</td><td>{counts.get("buy",0)}</td></tr>
<tr><td>Sell</td><td>{counts.get("sell",0)}</td></tr>
<tr><td>Swap</td><td>{counts.get("swap",0)}</td></tr>
<tr><td>Income</td><td>{counts.get("income",0)}</td></tr>
<tr><td>Transfer</td><td>{counts.get("transfer",0)}</td></tr>
</table>

<div class="alert warning">
⚠️ <strong>{taxable_events} events are likely taxable.</strong>
</div>

<div class="alert success">
💰 <strong>Estimated net USD activity:</strong> ${net_usd}
</div>

<div class="footer">
Generated by TaxLabs — clarity before compliance.
</div>

</div>
</body>
</html>
"""

    with open(output_html_path, "w", encoding="utf-8") as f:
        f.write(html)
